export class queryList {
  GET_STORE_LIST_QUERY: string = `SELECT ID, "NAME" FROM BMS.STORE`;

  SAVE_STORE_QUERY: string = `INSERT INTO bms.store(name, address,  created_on, created_by) VALUES($1, $2, $3, $4)`;

  GET_BOOK_LIST_QUERY: string = `SELECT ID, TITLE, DESCRIPTION, AUTHOR, PUBLISHER, PAGES, STORE_CODE, CREATED_ON, CREATED_BY FROM BMS.BOOK`;

  SAVE_BOOK_QUERY: string = ` INSERT INTO BMS.BOOK (TITLE, DESCRIPTION, AUTHOR, PUBLISHER, PAGES, STORE_CODE, CREATED_BY , CREATED_ON) VALUES($1, $2, $3, $4, $5 , $6 , $7 , $8)`;

  GET_BOOK_DETAILS_QUERY: string = `SELECT ID, TITLE, DESCRIPTION, AUTHOR, PUBLISHER, PAGES, STORE_CODE, CREATED_ON, CREATED_BY FROM BMS.BOOK INNER JOIN  BMS.STORE ON BOOK.STORE_CODE  = STORE.STORE_CODE WHERE BOOK_ID =$1`;

  UPDATE_STORE_QUERY: string = `UPDATE BMS.BOOK SET TITLE=$1, DESCRIPTION=$2, AUTHOR=$3, PUBLISHER=$4,PAGES=$5, STORE_CODE=$6, CREATED_BY=$7 , CREATED_ON=$8 WHERE BOOK_ID=$9`;

  DELETE_BOOK_QUERY: string = `DELETE FROM BMS.BOOK WHERE BOOK_ID=$1`;

  AUDIT_QUERY: string = `INSERT INTO BMS.APP_AUDIT (AUDIT_ACTION, AUDIT_DATA, AUDIT_STATUS, AUDIT_ERROR , AUDIT_BY, AUDIT_ON) VALUES($1, $2, $3, $4, $5, $6)`;

  GET_USER_LIST_QUERY: string = `SELECT USER_ID, USERNAME, EMAIL, FIRST_NAME, LAST_NAME, ACTIVE FROM BMS.APP_USER`;

  SAVE_USER_QUERY: string = `INSERT INTO BMS.APP_USER (USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, CREATED_ON, CREATED_BY) VALUES($1, $2, $3, $4, $5, $6, $7)  returning *`;

  IS_USER_EXIST_QUERY: string = `SELECT COUNT(ID) FROM BMS.APP_USER WHERE LOWER(USERNAME) =LOWER($1) OR LOWER(EMAIL)=LOWER($2)`;

  SIGN_IN_QUERY: string = `SELECT ID, USERNAME, PASSWORD , EMAIL, FIRST_NAME, LAST_NAME, ACTIVE FROM BMS.USER WHERE LOWER(EMAIL) = LOWER($1) AND ACTIVE = 1`;

  GET_USER_ROLE_QUERY: string = `SELECT "NAME" FROM BMS."ROLE"`;
  GET_USER_BY_EMAIL_QUERY: string = `SELECT u.ID as id, u.USERNAME as username, u.EMAIL as email, u.FIRST_NAME as firstName, u.LAST_NAME as lastName, u.ACTIVE as active,r.NAME as role FROM BMS.USER AS u JOIN BMS.ROLE as r ON u.ROLE_ID = r.ID WHERE LOWER(u.EMAIL) = LOWER($1) AND u.ACTIVE = 1`;
}